name: Prettier
on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '43 9 * * 2'
jobs:
  format:
    name: Run prettier scanning
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          
      - name: Run prettier
        run: |-
          npx prettier --write .*

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git commit -am "Automated changes- Prettier"
          git push
